sudo: false
env: RELEASE_TESTING=1
language: perl
perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
matrix:
  include:
    - perl: 5.22
      env: COVERAGE=1
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
install:
  - cpanm Test::CheckManifest Test::Pod::Coverage Test::Pod --quiet --notest
  - cpanm --quiet --installdeps --notest .
